In [2]:
import pandas as pd
data = pd.read_csv("creditApprovalUCI.csv")

#data.info()
data.A14.dtype
data.A8.dtype

categorical = [ i for i in data.columns if data [i].dtype=="0"] #범주형 변수
numeric = [i for i in data.columns if data[i].dtype !="0"] #수치형 변수
data[numeric] #data[categorical]

#Encoding
data[ categorical ] #na.nan
data.A1.isnull().sum() #mean()은 어제했던 방식
data.A1.value_counts()

tmp = data.A1.dropna() #"결측치를 잘 날린다"??
tmp
tmp2 = pd.get_dummies(tmp) #One Hot Encoding, drop_first=True # 이 부분 이상해서 "#"넣어서 스킵함 #오류 뜰 때가 있음 처음에는 안뜨나?? #런타임 다시 시작하기를 하면 오류가 사라진다!!
tmp2

import numpy as np
x=np.argmax( tmp2.values, axis=1 )#2d array 입력

#A6에 대해서 OHE 적용 (결측지 최빈값으로 대체)
tmp3 = pd.get_dummies(data.A6.fillna("c")) # 참고로 9개의 빈값을 가지고 있음  기존 A6의 c의 개수는 137개 tmp3의 c의 개수는 146
#즉, fillna()는 최빈값으로 대체
tmp3.shape
x=np.argmax(tmp3.values, axis=1)
x
#참고용: LabeEncooder : 컬럼 개수는 고저, 범주가 숫자로 ...
#데이터프레임.컬럼.map(딕셔너리)

array([12, 10, 10, 12, 12,  9, 11,  2,  8, 12,  1,  1,  8,  8, 10,  8,  9,
       10,  3,  2,  1,  1,  1, 13, 10,  1,  6,  3,  4, 12,  0, 13,  6,  4,
       10, 12,  2, 13,  2,  5,  1,  1, 12, 12,  1,  1, 10,  2,  6,  1,  1,
       10, 12, 12,  2, 12,  2,  6, 13, 10,  9,  3, 10, 10,  2,  2,  1,  9,
       12, 13,  4,  3,  2,  9,  1, 10,  0,  0,  8,  1,  5,  9,  9,  3,  0,
        1,  3,  0,  0,  7,  1,  1,  0,  1,  1,  6,  0,  1, 10, 10,  1,  1,
       10,  8,  6,  4,  8,  0, 13,  1, 12,  5, 12,  8,  1, 10, 10,  8,  9,
        2, 10,  2,  0, 10, 10, 13,  9, 10,  6, 12,  4,  1,  4,  1, 10, 10,
        0,  9, 12, 10,  2,  7,  2, 12,  2,  2, 10, 10,  1,  1,  2, 10,  9,
        1,  2,  7, 13,  4,  8,  9, 13,  9, 13,  4, 10, 10, 10,  2, 10,  3,
        0,  1,  8,  8, 10, 12,  0,  0, 10,  0,  1,  6, 10,  1, 10,  1,  0,
        1,  1, 10,  1,  6, 13, 12,  6,  1, 13, 12,  0, 13, 10,  6,  1, 10,
       12, 10,  1, 10,  8,  1,  2,  3,  5,  6,  2,  0,  2,  5,  4,  1,  0,
        4,  0,  0, 10,  1

In [20]:
from sklearn.tree import DecisionTreeClassifier
#creditset.scv, default10yr가 target, loan, age, income이 X변수
credit = pd.read_csv("creditset.csv")
y = pd.get_dummies(credit.default10yr)
X = credit[["loan", "age", "income"]]
dt = DecisionTreeClassifier()
dt.fit(X, y) #modeling
dt.predict(X) #predict

array([[1, 0],
       [1, 0],
       [1, 0],
       ...,
       [0, 1],
       [1, 0],
       [1, 0]], dtype=uint8)

In [24]:
from sklearn.tree import DecisionTreeClassifier

# creditset.scv 파일을 읽어옵니다.
credit = pd.read_csv("creditset.csv")

# 목표 변수인 'default10yr'을 y로 설정합니다.
y = credit["default10yr"]

# 독립 변수인 'loan', 'age', 'income'을 X로 설정합니다.
X = credit[["loan", "age", "income"]]

# 의사결정트리 모델을 만듭니다.
dt = DecisionTreeClassifier()

# 모델을 훈련합니다.
dt.fit(X, y)

# 훈련된 모델로 예측을 수행합니다.
predictions = dt.predict(X)

# 예측 결과를 확인합니다.
print(predictions)


[0 0 0 ... 1 0 0]
