# ANN 시작하기

In [ ]:
mortDefault.zip를 업로드

!unzip mortDefault.zip
(이거 시험 그대로 나온다)
1) @@@ -> np.nan
2) qqq -> np.nan
3) dropna()
4) 데이터프레임. 컬럼 . astype('int64')
5) y: default, X: creditScore, .....
6) 파티셔닝
7) 스케일링
8) ANN
9) classification_report로 테스트에 대한 결과
10) GridSearch: hidden_Layer_sizes

다음 시간에 비지도 학습

In [ ]:
import pandas as pd
data = pd.read_csv('mortDefault.csv')

import numpy as np

data= data.replace("@@@", np.nan, regex=True)
data= data.replace("qqq", np.nan, regex=True)
data.dropna(inplace=True)
data["creditScore"]=data["creditScore"].astype('int')

<ipython-input-9-a80e740790c9>:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('mortDefault.csv')


In [ ]:
X = data[["creditScore","houseAge","yearsEmploy","ccDebt"]]
y=data.default

In [ ]:
from sklearn.model_selection import train_test_split
X_train X_test y_train y_test = train_test_split(X,y,test_size=0.2)

#from sklearn.Scalering import MinMaxScaler StandardScaler

SyntaxError: ignored

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
# 연습용 데이터
x = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0],[1],[1],[1]])
print(x)
print(y)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]
[[0]
 [1]
 [1]
 [1]]


In [ ]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier( hidden_layer_sizes=(3,1) ) #은니층 3개 다음이 1개인 구조
model.fit( x,y)

#model.score(x,y)    # 정분류율
#model.predict(x)  # x 예측

#활성화 함수는 렐루함수 tanh함수 시그모이드함수 3가지

#model.coefs_        # 가중치??
#ANN 스케일링필수

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


array([1, 1, 1, 1])

#연습 1: creditset.csv에 DNN 적용, MLPClassifier와 비교

In [ ]:
-아래 예제를 참고, creditset에 대해서 ANN
-파티셔닝 8:2
-MinMaxScaing
-신경망 구조는...
-test에 대한 정분류
-classification_report로 결과,,,,

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

csv_data = pd.read_csv("creditset.csv")
X = csv_data.iloc[:, 1:4 ]
y  = csv_data.iloc[:, 5 ]


In [ ]:
#Partitioning
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42 )
scaler = preprocessing.MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.fit_transform( X_train)
X_test  = scaler.fit_transform( X_test  )

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(6,3))
mlp.fit(X_train,y_train)
print(mlp.score(X_test,y_test))

predictions = mlp.predict(X_test)
np.mean( predictions == y_test )

#mlp.coefs_

0.9366666666666666


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.9366666666666666

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print( confusion_matrix(y_test,predictions) )
print('\n', classification_report(y_test,predictions) )

[[507   1]
 [ 27  65]]

               precision    recall  f1-score   support

           0       0.95      1.00      0.97       508
           1       0.98      0.71      0.82        92

    accuracy                           0.95       600
   macro avg       0.97      0.85      0.90       600
weighted avg       0.95      0.95      0.95       600



In [ ]:
csv_data.default10yr.value_counts()/2000

0    0.8585
1    0.1415
Name: default10yr, dtype: float64

#연습 2: 반도체 제조 data.csv에 DNN 적용, ML과 비교

- sklearn

In [ ]:
import pandas as pd
import numpy as np
csv_data = pd.read_csv("data.csv")
csv_data.shape

(1567, 49)

In [ ]:
csv_data['Pass.Fail'].value_counts()

0    1463
1     104
Name: Pass.Fail, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

X = csv_data.iloc[:, 0:48 ]   #모든행, 1열~48열까지
y = csv_data.iloc[:, 48 ]    #모든 행, 49열 인덱싱

#Partitioning
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42 )
scaler = preprocessing.MinMaxScaler()
X_train = scaler.fit_transform( X_train)
X_test  = scaler.fit_transform( X_test  )

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

#DT
dt1 = DecisionTreeClassifier().fit(X_train, y_train)
pred = dt1.predict( X_test)
print('DT', np.mean( pred == y_test ))

#RF
rf = RandomForestClassifier(n_estimators=300, random_state=42).fit(X_train, y_train)
predicted = rf.predict(X_test)
print('RF', np.mean( predicted == y_test ))

#KNN
knn = KNeighborsClassifier().fit(X_train, y_train)  #k=5
predicted = knn.predict(X_test)
print('KNN', np.mean( predicted == y_test ))

#SVM
svm = SVC().fit(X_train, y_train)
predicted = svm.predict(X_test)
print('SVM', np.mean( predicted == y_test ))

#ANN
mlp = MLPClassifier(hidden_layer_sizes=(24,12,6)).fit(X_train,y_train)
predictions = mlp.predict(X_test)
print('ANN',np.mean( predictions == y_test ))

DT 0.5711252653927813
RF 0.9299363057324841
KNN 0.9320594479830149
SVM 0.9341825902335457
ANN 0.9341825902335457


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
내일은 분류 다 해보고